# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ox7nTOj1ZE5fwAYZr2u-8MiRf9GcArmO
"""

nps_pesquisa = int(input("Olá, avalie nosso atendimento dando uma nota de 0 a 100: "))

if nps_pesquisa <= 0 or nps_pesquisa > 100:
    print("Nota inválida. Insira um valor entre 0 e 100.")
elif nps_pesquisa < 70:
    print("Atendimento insatisfatório")
elif 70 <= nps_pesquisa < 90:
    print("Atendimento neutro")
elif 90 <= nps_pesquisa <= 100:
    print("Atendimento de Qualidade")