table dCalendario
	lineageTag: a1b2c3d4-e5f6-7890-abcd-ef1234567890

	column Date
		dataType: dateTime
		isKey
		formatString: Short Date
		lineageTag: b2c3d4e5-f6a7-8901-bcde-f12345678901
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

	column Ano
		dataType: int64
		formatString: 0
		lineageTag: c3d4e5f6-a7b8-9012-cdef-123456789012
		summarizeBy: none
		sourceColumn: Ano

		annotation SummarizationSetBy = Automatic

	column 'Mes Numero'
		dataType: int64
		formatString: 0
		lineageTag: d4e5f6a7-b8c9-0123-def0-234567890123
		summarizeBy: none
		sourceColumn: Mes Numero

		annotation SummarizationSetBy = Automatic

	column 'Mes Nome'
		dataType: string
		lineageTag: e5f6a7b8-c9d0-1234-ef01-345678901234
		summarizeBy: none
		sourceColumn: Mes Nome
		sortByColumn: 'Mes Numero'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Ano-Mes
		dataType: string
		lineageTag: a7b8c9d0-e1f2-3456-0123-567890123456
		summarizeBy: none
		sourceColumn: Ano-Mes
		sortByColumn: 'Mes Numero'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Trimestre
		dataType: string
		lineageTag: b8c9d0e1-f2a3-4567-1234-678901234567
		summarizeBy: none
		sourceColumn: Trimestre

		annotation SummarizationSetBy = Automatic

	column Ano-Trimestre
		dataType: string
		lineageTag: c9d0e1f2-a3b4-5678-2345-789012345678
		summarizeBy: none
		sourceColumn: Ano-Trimestre
		sortByColumn: Date

		annotation SummarizationSetBy = Automatic

	column Semestre
		dataType: string
		lineageTag: a3b4c5d6-e7f8-9012-6789-123456789012
		summarizeBy: none
		sourceColumn: Semestre

		annotation SummarizationSetBy = Automatic

	hierarchy 'Hierarquia de Datas'
		lineageTag: f1e2d3c4-b5a6-7890-1234-567890abcdef

		level Ano
			lineageTag: a1a2a3a4-b1b2-c1c2-d1d2-e1e2e3e4e5e6
			column: Ano

		level Trimestre
			lineageTag: b1b2b3b4-c1c2-d1d2-e1e2-f1f2f3f4f5f6
			column: Trimestre

		level 'Mes Nome'
			lineageTag: c1c2c3c4-d1d2-e1e2-f1f2-a1a2a3a4a5a6
			column: 'Mes Nome'

	partition dCalendario = m
		mode: import
		source =
				let
				    _inicio   = #date(2020, 1, 1),
				    _fim      = #date(2024, 12, 31),
				    NbDays    = Duration.Days(_fim - _inicio) + 1,
				    Datas     = List.Dates(_inicio, NbDays, #duration(1, 0, 0, 0)),
				    Tabela    = Table.FromList(Datas, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    TipoDate  = Table.TransformColumnTypes(Tabela, {{"Date", type datetime}}),
				    AddAno    = Table.AddColumn(TipoDate,  "Ano",           each Date.Year([Date]),                                                                        Int64.Type),
				    AddMesNum = Table.AddColumn(AddAno,    "Mes Numero",    each Date.Month([Date]),                                                                       Int64.Type),
				    AddMesNom = Table.AddColumn(AddMesNum, "Mes Nome",      each Text.Proper(Text.Start(Date.MonthName([Date], "pt-BR"), 3)),                              type text),
				    AddAnoMes = Table.AddColumn(AddMesNom, "Ano-Mes",       each Text.From(Date.Year([Date])) & "-" & Text.PadStart(Text.From(Date.Month([Date])), 2, "0"), type text),
				    AddTrim   = Table.AddColumn(AddAnoMes, "Trimestre",     each "T" & Text.From(Date.QuarterOfYear([Date])),                                             type text),
				    AddAnoTri = Table.AddColumn(AddTrim,   "Ano-Trimestre", each Text.From(Date.Year([Date])) & " T" & Text.From(Date.QuarterOfYear([Date])),             type text),
				    AddSem    = Table.AddColumn(AddAnoTri, "Semestre",      each if Date.Month([Date]) <= 6 then "1o Sem" else "2o Sem",                                  type text)
				in
				    AddSem

	annotation PBI_ResultType = Table

